name: Update Gvsbuild
on:
  workflow_dispatch:
  schedule:
    # min hour dom month dow
    - cron:  '0 5 * * 3'
  # temp for testing
  pull_request:
    branches: [main]
env:
  python_version: '3.12'
  file: '.github/workflows/full-build.yml'
  yaml_key: '.jobs.windows.env.gvsbuild_version'

permissions:
  pull-requests: write

jobs:

  updater:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: ${{ env.python_version }}
      - name: Get current version
        run: |
          echo "current_version=$(yq ${{ env.yaml_key }} ${{ env.file }})" >> "GITHUB_ENV"
      - name: Get latest version
        run: |
          pip install --constraint=.github/constraints.txt lastversion
          echo "latest_version=$(python -m lastversion gvsbuild)" >> "GITHUB_ENV"
      - name: Update version
        if: ${{ env.current_version != env.latest_version }}
        run: |
          sed -i "$(yq ${{ env.yaml_key }} | line' "${{ env.file }}")s/${{ env.current_version }}/${{ env.latest_version }}/" "${{ env.file }}"
      - name: Configure Git
        if: ${{ env.current_version != env.latest_version }}
        run: |
          git config user.email "ci@gaphor.org"
          git config user.name "GitHub Actions"
      - name: Push changes to new branch
        if: ${{ env.current_version != env.latest_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch -c gvsbuild-updates-${{ github.run_id }}
          git add ${{ env.file }}
          git commit -m "Bump Gvsbuild to version ${{ env.latest_version }}"
          git push origin gvsbuild-updates-${{ github.run_id }}
      - name: Create Pull Request
        if: ${{ env.current_version != env.latest_version }}
        run: |
          gh pr create -B main -H gvsbuild-updates-${{ github.run_id }} \
            --title 'Bump Gvsbuild from ${{ env.current_version }} to ${{ env.latest_version }}' \
            --body 'This PR updates the Gvsbuild version.'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
